export const sampleGlobalData = [
  {
    name: "Linus Torvalds",
    fullname: "Linus Benedict Torvalds",
    location: "Helsinki, Finland",
    contributions: 100000,
    login: "torvalds",
    avatarUrl: "https://github.com/torvalds.png",
    company: "Linux Foundation",
  },
  {
    name: "Guido van Rossum",
    fullname: "Guido van Rossum",
    location: "San Francisco, CA",
    contributions: 90000,
    login: "gvanrossum",
    avatarUrl: "https://github.com/gvanrossum.png",
    company: "Dropbox",
  },
  {
    name: "Brendan Eich",
    fullname: "Brendan Eich",
    location: "San Francisco, CA",
    contributions: 80000,
    login: "BrendanEich",
    avatarUrl: "https://github.com/BrendanEich.png",
    company: "Brave Software",
  },
  {
    name: "Ryan Dahl",
    fullname: "Ryan Dahl",
    location: "Berlin, Germany",
    contributions: 70000,
    login: "ry",
    avatarUrl: "https://github.com/ry.png",
    company: "Deno Land Inc.",
  },
  {
    name: "Anders Hejlsberg",
    fullname: "Anders Hejlsberg",
    location: "Seattle, WA",
    contributions: 60000,
    login: "ahejlsberg",
    avatarUrl: "https://github.com/ahejlsberg.png",
    company: "Microsoft",
  },
  {
    name: "James Gosling",
    fullname: "James Gosling",
    location: "Calgary, Canada",
    contributions: 50000,
    login: "JamesGosling",
    avatarUrl: "https://github.com/JamesGosling.png",
    company: "Amazon Web Services",
  },
  {
    name: "Bjarne Stroustrup",
    fullname: "Bjarne Stroustrup",
    location: "New York, NY",
    contributions: 40000,
    login: "BjarneStroustrup",
    avatarUrl: "https://github.com/BjarneStroustrup.png",
    company: "Morgan Stanley",
  },
  {
    name: "Dennis Ritchie",
    fullname: "Dennis MacAlistair Ritchie",
    location: "Murray Hill, NJ",
    contributions: 30000,
    login: "dmr",
    avatarUrl: "https://github.com/dmr.png",
    company: "Bell Labs",
  },
  {
    name: "Ken Thompson",
    fullname: "Kenneth Lane Thompson",
    location: "Mountain View, CA",
    contributions: 20000,
    login: "ken",
    avatarUrl: "https://github.com/ken.png",
    company: "Google",
  },
  {
    name: "John Carmack",
    fullname: "John D. Carmack II",
    location: "Dallas, TX",
    contributions: 10000,
    login: "ID_AA_Carmack",
    avatarUrl: "https://github.com/ID_AA_Carmack.png",
    company: "Oculus VR",
  },
]

// Afghanistan-specific sample data
export const sampleCountryData = {
  name: "Afghanistan",
  users: [
    {
      rank: 1,
      name: "Ahmad Ahmadi",
      login: "ahmadahmadi",
      avatarUrl: "https://github.com/ahmadahmadi.png",
      contributions: 8765,
      company: "Kabul Tech Solutions",
      location: "Kabul, Afghanistan",
    },
    {
      rank: 2,
      name: "Fatima Noori",
      login: "fnoori",
      avatarUrl: "https://github.com/fnoori.png",
      contributions: 7654,
      company: "Afghan Developers Association",
      location: "Herat, Afghanistan",
    },
    {
      rank: 3,
      name: "Mohammad Karimi",
      login: "mkarimi",
      avatarUrl: "https://github.com/mkarimi.png",
      contributions: 6543,
      company: "Code Afghanistan",
      location: "Mazar-i-Sharif, Afghanistan",
    },
    {
      rank: 4,
      name: "Zahra Mohammadi",
      login: "zmohammadi",
      avatarUrl: "https://github.com/zmohammadi.png",
      contributions: 5432,
      company: "Afghanistan IT Solutions",
      location: "Kandahar, Afghanistan",
    },
    {
      rank: 5,
      name: "Ali Akbari",
      login: "aliakbari",
      avatarUrl: "https://github.com/aliakbari.png",
      contributions: 4321,
      company: "Kabul University",
      location: "Kabul, Afghanistan",
    },
    {
      rank: 6,
      name: "Nadia Hashimi",
      login: "nhashimi",
      avatarUrl: "https://github.com/nhashimi.png",
      contributions: 3210,
      company: "Afghan Women in Tech",
      location: "Jalalabad, Afghanistan",
    },
    {
      rank: 7,
      name: "Omar Sadat",
      login: "omarsadat",
      avatarUrl: "https://github.com/omarsadat.png",
      contributions: 2987,
      company: "Herat Tech Hub",
      location: "Herat, Afghanistan",
    },
    {
      rank: 8,
      name: "Leila Ahmadzai",
      login: "lahmadzai",
      avatarUrl: "https://github.com/lahmadzai.png",
      contributions: 2765,
      company: "Afghanistan Coders",
      location: "Kabul, Afghanistan",
    },
    {
      rank: 9,
      name: "Hamid Rahimi",
      login: "hrahimi",
      avatarUrl: "https://github.com/hrahimi.png",
      contributions: 2543,
      company: "Afghan Software Solutions",
      location: "Mazar-i-Sharif, Afghanistan",
    },
    {
      rank: 10,
      name: "Sara Nazari",
      login: "snazari",
      avatarUrl: "https://github.com/snazari.png",
      contributions: 2321,
      company: "Kabul Developers Community",
      location: "Kabul, Afghanistan",
    },
  ],
}
